// This file is autogenerated by VESC Tool

#ifndef APPCONF_DEFAULT_H_
#define APPCONF_DEFAULT_H_

// VESC ID
#ifndef APPCONF_CONTROLLER_ID
#define APPCONF_CONTROLLER_ID 0
#endif

// Timeout
#ifndef APPCONF_TIMEOUT_MSEC
#define APPCONF_TIMEOUT_MSEC 1000
#endif

// Timeout Brake Current
#ifndef APPCONF_TIMEOUT_BRAKE_CURRENT
#define APPCONF_TIMEOUT_BRAKE_CURRENT 0
#endif

// Send CAN Status
#ifndef APPCONF_SEND_CAN_STATUS
#define APPCONF_SEND_CAN_STATUS 0
#endif

// Can Status Rate
#ifndef APPCONF_SEND_CAN_STATUS_RATE_HZ
#define APPCONF_SEND_CAN_STATUS_RATE_HZ 500
#endif

// CAN Baud Rate
#ifndef APPCONF_CAN_BAUD_RATE
#define APPCONF_CAN_BAUD_RATE 2
#endif

// APP to Use
#ifndef APPCONF_APP_TO_USE
#define APPCONF_APP_TO_USE 3
#endif

// Control Type
#ifndef APPCONF_PPM_CTRL_TYPE
#define APPCONF_PPM_CTRL_TYPE 0
#endif

// PID Max ERPM
#ifndef APPCONF_PPM_PID_MAX_ERPM
#define APPCONF_PPM_PID_MAX_ERPM 15000
#endif

// Input Deadband
#ifndef APPCONF_PPM_HYST
#define APPCONF_PPM_HYST 0.15
#endif

// Pulselength Start
#ifndef APPCONF_PPM_PULSE_START
#define APPCONF_PPM_PULSE_START 1
#endif

// Pulselength End
#ifndef APPCONF_PPM_PULSE_END
#define APPCONF_PPM_PULSE_END 2
#endif

// Pulselength Center
#ifndef APPCONF_PPM_PULSE_CENTER
#define APPCONF_PPM_PULSE_CENTER 1.5
#endif

// Median Filter
#ifndef APPCONF_PPM_MEDIAN_FILTER
#define APPCONF_PPM_MEDIAN_FILTER 1
#endif

// Safe Start
#ifndef APPCONF_PPM_SAFE_START
#define APPCONF_PPM_SAFE_START 1
#endif

// Throttle Expo
#ifndef APPCONF_PPM_THROTTLE_EXP
#define APPCONF_PPM_THROTTLE_EXP 0
#endif

// Throttle Expo Brake
#ifndef APPCONF_PPM_THROTTLE_EXP_BRAKE
#define APPCONF_PPM_THROTTLE_EXP_BRAKE 0
#endif

// Throttle Expo Mode
#ifndef APPCONF_PPM_THROTTLE_EXP_MODE
#define APPCONF_PPM_THROTTLE_EXP_MODE 2
#endif

// Positive Ramping Time
#ifndef APPCONF_PPM_RAMP_TIME_POS
#define APPCONF_PPM_RAMP_TIME_POS 0.9
#endif

// Negative Ramping Time
#ifndef APPCONF_PPM_RAMP_TIME_NEG
#define APPCONF_PPM_RAMP_TIME_NEG 0.3
#endif

// Multiple VESCs Over CAN
#ifndef APPCONF_PPM_MULTI_ESC
#define APPCONF_PPM_MULTI_ESC 0
#endif

// Traction Control
#ifndef APPCONF_PPM_TC
#define APPCONF_PPM_TC 0
#endif

// TC Max ERPM Difference
#ifndef APPCONF_PPM_TC_MAX_DIFF
#define APPCONF_PPM_TC_MAX_DIFF 3000
#endif

// Control Type
#ifndef APPCONF_ADC_CTRL_TYPE
#define APPCONF_ADC_CTRL_TYPE 0
#endif

// Input Deadband
#ifndef APPCONF_ADC_HYST
#define APPCONF_ADC_HYST 0.15
#endif

// ADC1 Min Voltage
#ifndef APPCONF_ADC_VOLTAGE_START
#define APPCONF_ADC_VOLTAGE_START 0.9
#endif

// ADC1 Max Voltage
#ifndef APPCONF_ADC_VOLTAGE_END
#define APPCONF_ADC_VOLTAGE_END 3
#endif

// ADC1 Center Voltage
#ifndef APPCONF_ADC_VOLTAGE_CENTER
#define APPCONF_ADC_VOLTAGE_CENTER 2
#endif

// ADC2 Min Voltage
#ifndef APPCONF_ADC_VOLTAGE2_START
#define APPCONF_ADC_VOLTAGE2_START 0.9
#endif

// ADC2 Max Voltage
#ifndef APPCONF_ADC_VOLTAGE2_END
#define APPCONF_ADC_VOLTAGE2_END 3
#endif

// Use Filter
#ifndef APPCONF_ADC_USE_FILTER
#define APPCONF_ADC_USE_FILTER 1
#endif

// Safe Start
#ifndef APPCONF_ADC_SAFE_START
#define APPCONF_ADC_SAFE_START 1
#endif

// Invert Cruise Control Button
#ifndef APPCONF_ADC_CC_BUTTON_INVERTED
#define APPCONF_ADC_CC_BUTTON_INVERTED 0
#endif

// Invert Reverse Button
#ifndef APPCONF_ADC_REV_BUTTON_INVERTED
#define APPCONF_ADC_REV_BUTTON_INVERTED 0
#endif

// Invert ADC1 Voltage
#ifndef APPCONF_ADC_VOLTAGE_INVERTED
#define APPCONF_ADC_VOLTAGE_INVERTED 0
#endif

// Invert ADC2 Voltage
#ifndef APPCONF_ADC_VOLTAGE2_INVERTED
#define APPCONF_ADC_VOLTAGE2_INVERTED 0
#endif

// Throttle Expo
#ifndef APPCONF_ADC_THROTTLE_EXP
#define APPCONF_ADC_THROTTLE_EXP 0
#endif

// Throttle Expo Brake
#ifndef APPCONF_ADC_THROTTLE_EXP_BRAKE
#define APPCONF_ADC_THROTTLE_EXP_BRAKE 0
#endif

// Throttle Expo Mode
#ifndef APPCONF_ADC_THROTTLE_EXP_MODE
#define APPCONF_ADC_THROTTLE_EXP_MODE 2
#endif

// Positive Ramping Time
#ifndef APPCONF_ADC_RAMP_TIME_POS
#define APPCONF_ADC_RAMP_TIME_POS 0.9
#endif

// Negative Ramping Time
#ifndef APPCONF_ADC_RAMP_TIME_NEG
#define APPCONF_ADC_RAMP_TIME_NEG 0.3
#endif

// Multiple VESCs Over CAN
#ifndef APPCONF_ADC_MULTI_ESC
#define APPCONF_ADC_MULTI_ESC 0
#endif

// Traction Control
#ifndef APPCONF_ADC_TC
#define APPCONF_ADC_TC 0
#endif

// TC Max ERPM Difference
#ifndef APPCONF_ADC_TC_MAX_DIFF
#define APPCONF_ADC_TC_MAX_DIFF 3000
#endif

// Update Rate
#ifndef APPCONF_ADC_UPDATE_RATE_HZ
#define APPCONF_ADC_UPDATE_RATE_HZ 500
#endif

// Baudrate
#ifndef APPCONF_UART_BAUDRATE
#define APPCONF_UART_BAUDRATE 115200
#endif

// Control Type
#ifndef APPCONF_CHUK_CTRL_TYPE
#define APPCONF_CHUK_CTRL_TYPE 1
#endif

// Input Deadband
#ifndef APPCONF_CHUK_HYST
#define APPCONF_CHUK_HYST 0.15
#endif

// Positive Ramping Time
#ifndef APPCONF_CHUK_RAMP_TIME_POS
#define APPCONF_CHUK_RAMP_TIME_POS 0.9
#endif

// Negative Ramping Time
#ifndef APPCONF_CHUK_RAMP_TIME_NEG
#define APPCONF_CHUK_RAMP_TIME_NEG 0.3
#endif

// ERPM Per Second Cruise Control
#ifndef APPCONF_STICK_ERPM_PER_S_IN_CC
#define APPCONF_STICK_ERPM_PER_S_IN_CC 3000
#endif

// Throttle Expo
#ifndef APPCONF_CHUK_THROTTLE_EXP
#define APPCONF_CHUK_THROTTLE_EXP 0
#endif

// Throttle Expo Brake
#ifndef APPCONF_CHUK_THROTTLE_EXP_BRAKE
#define APPCONF_CHUK_THROTTLE_EXP_BRAKE 0
#endif

// Throttle Expo Mode
#ifndef APPCONF_CHUK_THROTTLE_EXP_MODE
#define APPCONF_CHUK_THROTTLE_EXP_MODE 2
#endif

// Multiple VESCs Over CAN
#ifndef APPCONF_CHUK_MULTI_ESC
#define APPCONF_CHUK_MULTI_ESC 0
#endif

// Traction Control
#ifndef APPCONF_CHUK_TC
#define APPCONF_CHUK_TC 0
#endif

// TC Max ERPM Difference
#ifndef APPCONF_CHUK_TC_MAX_DIFF
#define APPCONF_CHUK_TC_MAX_DIFF 3000
#endif

// Speed
#ifndef APPCONF_NRF_SPEED
#define APPCONF_NRF_SPEED 2
#endif

// TX Power
#ifndef APPCONF_NRF_POWER
#define APPCONF_NRF_POWER 3
#endif

// CRC
#ifndef APPCONF_NRF_CRC
#define APPCONF_NRF_CRC 1
#endif

// Retry Delay
#ifndef APPCONF_NRF_RETR_DELAY
#define APPCONF_NRF_RETR_DELAY 0
#endif

// Retries
#ifndef APPCONF_NRF_RETRIES
#define APPCONF_NRF_RETRIES 3
#endif

// Radio Channel
#ifndef APPCONF_NRF_CHANNEL
#define APPCONF_NRF_CHANNEL 76
#endif

// Address 0
#ifndef APPCONF_NRF_ADDR_B0
#define APPCONF_NRF_ADDR_B0 198
#endif

// Address 1
#ifndef APPCONF_NRF_ADDR_B1
#define APPCONF_NRF_ADDR_B1 199
#endif

// Address 2
#ifndef APPCONF_NRF_ADDR_B2
#define APPCONF_NRF_ADDR_B2 0
#endif

// Send ACK
#ifndef APPCONF_NRF_SEND_CRC_ACK
#define APPCONF_NRF_SEND_CRC_ACK 1
#endif

// Control Type
#ifndef APPCONF_ADC_BOOST_CTRL_TYPE
#define APPCONF_ADC_BOOST_CTRL_TYPE 0
#endif

// Input Deadband
#ifndef APPCONF_ADC_BOOST_HYST
#define APPCONF_ADC_BOOST_HYST 0.15
#endif

// ADC1 Min Voltage
#ifndef APPCONF_ADC_BOOST_VOLTAGE_START
#define APPCONF_ADC_BOOST_VOLTAGE_START 0.9
#endif

// ADC1 Max Voltage
#ifndef APPCONF_ADC_BOOST_VOLTAGE_END
#define APPCONF_ADC_BOOST_VOLTAGE_END 3
#endif

// ADC1 Center Voltage
#ifndef APPCONF_ADC_BOOST_VOLTAGE_CENTER
#define APPCONF_ADC_BOOST_VOLTAGE_CENTER 2
#endif

// ADC2 Min Voltage
#ifndef APPCONF_ADC_BOOST_VOLTAGE2_START
#define APPCONF_ADC_BOOST_VOLTAGE2_START 0.9
#endif

// ADC2 Max Voltage
#ifndef APPCONF_ADC_BOOST_VOLTAGE2_END
#define APPCONF_ADC_BOOST_VOLTAGE2_END 3
#endif

// Use Filter
#ifndef APPCONF_ADC_BOOST_USE_FILTER
#define APPCONF_ADC_BOOST_USE_FILTER 1
#endif

// Safe Start
#ifndef APPCONF_ADC_BOOST_SAFE_START
#define APPCONF_ADC_BOOST_SAFE_START 1
#endif

// Invert Cruise Control Button
#ifndef APPCONF_ADC_BOOST_CC_BUTTON_INVERTED
#define APPCONF_ADC_BOOST_CC_BUTTON_INVERTED 0
#endif

// Invert Reverse Button
#ifndef APPCONF_ADC_BOOST_REV_BUTTON_INVERTED
#define APPCONF_ADC_BOOST_REV_BUTTON_INVERTED 0
#endif

// Invert ADC1 Voltage
#ifndef APPCONF_ADC_BOOST_VOLTAGE_INVERTED
#define APPCONF_ADC_BOOST_VOLTAGE_INVERTED 0
#endif

// Invert ADC2 Voltage
#ifndef APPCONF_ADC_BOOST_VOLTAGE2_INVERTED
#define APPCONF_ADC_BOOST_VOLTAGE2_INVERTED 0
#endif

// Throttle Expo
#ifndef APPCONF_ADC_BOOST_THROTTLE_EXP
#define APPCONF_ADC_BOOST_THROTTLE_EXP 0
#endif

// Throttle Expo Brake
#ifndef APPCONF_ADC_BOOST_THROTTLE_EXP_BRAKE
#define APPCONF_ADC_BOOST_THROTTLE_EXP_BRAKE 0
#endif

// Throttle Expo Mode
#ifndef APPCONF_ADC_BOOST_THROTTLE_EXP_MODE
#define APPCONF_ADC_BOOST_THROTTLE_EXP_MODE 2
#endif

// Positive Ramping Time
#ifndef APPCONF_ADC_BOOST_RAMP_TIME_POS
#define APPCONF_ADC_BOOST_RAMP_TIME_POS 0.9
#endif

// Negative Ramping Time
#ifndef APPCONF_ADC_BOOST_RAMP_TIME_NEG
#define APPCONF_ADC_BOOST_RAMP_TIME_NEG 0.3
#endif

// Multiple VESCs Over CAN
#ifndef APPCONF_ADC_BOOST_MULTI_ESC
#define APPCONF_ADC_BOOST_MULTI_ESC 0
#endif

// Traction Control
#ifndef APPCONF_ADC_BOOST_TC
#define APPCONF_ADC_BOOST_TC 0
#endif

// TC Max ERPM Difference
#ifndef APPCONF_ADC_BOOST_TC_MAX_DIFF
#define APPCONF_ADC_BOOST_TC_MAX_DIFF 3000
#endif

// Update Rate
#ifndef APPCONF_ADC_BOOST_UPDATE_RATE_HZ
#define APPCONF_ADC_BOOST_UPDATE_RATE_HZ 480
#endif

// Maximum Boost Time
#ifndef APPCONF_ADC_BOOST_MAX_BOOST_TIME
#define APPCONF_ADC_BOOST_MAX_BOOST_TIME 15
#endif

// Boost Start
#ifndef APPCONF_ADC_BOOST_BOOST_START
#define APPCONF_ADC_BOOST_BOOST_START 0.8
#endif

// Boost Cooldown Factor
#ifndef APPCONF_ADC_BOOST_BOOST_COOLDOWN_FACTOR
#define APPCONF_ADC_BOOST_BOOST_COOLDOWN_FACTOR 5
#endif

// APPCONF_DEFAULT_H_
#endif

